
spring:
  datasource:
    name: test  #数据库名
    url: jdbc:mysql://47.103.48.29:3306/shanguojun?useSSL=false #url
    username: shanguojun #用户名
    password: SHANshan2020! #密码
    driver-class-name: com.mysql.jdbc.Driver  #数据库链接驱动

mybatis:
  mapper-locations: classpath:mapper/*.xml  #配置映射文件
  type-aliases-package: com.example.test.bean #配置实体类